name: Restrict Merge to Main
on:
  pull_request:
    branches:
      - main
jobs:
  restrict-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" == "development" ]]; then
            echo "✅ Valid PR: Source branch is development"
            exit 0
          else
            echo "❌ Error: Pull requests to 'main' must originate from 'development' branch"
            echo "Current source branch: ${{ github.head_ref }}"
            exit 1
          fi